//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAgency.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            this.HotelServices = new HashSet<HotelService>();
            this.TouristTrips = new HashSet<TouristTrip>();
        }
    
        public int IdHotel { get; set; }
        public string Name { get; set; }
        public string NumberOfStarsId { get; set; }
        public int CountryId { get; set; }
        public decimal PriceOneWeek { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual NumStar NumStar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelService> HotelServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TouristTrip> TouristTrips { get; set; }
    }
}
