//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAgency.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelService
    {
        public int IdHotSer { get; set; }
        public int HotelId { get; set; }
        public int ServiceId { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Service Service { get; set; }
    }
}
